### ISSUE TITLE
Bug: Enemy UI disappears after trainer battle

### ISSUE THREAD

**Issue by Cyndeon** [roguedex-dev/roguedex#23]
I use Opera GX and currently have the Extension without going through the official Opera GX Extensions (due to it still awaiting moderation as described in the Reddit post).

After fighting a trainer, the UI seems to disappear for enemies, but not for my own team.
This happened on round 5, 8 and 20 so far, all right after beating the trainer. I was playing on Classic. Not sure if that made the difference, but just in case it might be worth mentioning.

Refreshing the page brings the UI back again, but I have not found any other way to prevent the UI from disappearing.

**Comment by roguedex-dev** [comment]
Hey! Just release 2.2, make sure to upgrade and let me know if it still happens to you! I'll close the issue for now
