### ISSUE TITLE
Enemy UI disappears in google chrome just before loading another pokemon. 

### ISSUE THREAD

**Issue by Chromeuser19** [roguedex-dev/roguedex#24]
Hey, 

Enemy UI disappears after some time. It forces me to refresh the page. But it happens so fast ( 4-6 battles) that it makes the extension just unusable. Sadge :(

Cheers.

**Comment by roguedex-dev** [comment]
Just release 2.2 which fixes the issue! Feel free to re-open the issue here on GitHub if you find it still happens to you.
