### ISSUE TITLE
Extension not working on 'Continue' or reloading.

### ISSUE THREAD

**Issue by Eruyome** [roguedex-dev/roguedex#32]
The extension only works for me when starting a new run and only until I reload/refresh. When continuing a run the extension doesn't work, meaning the UI elements don't show up at all and I couldn't see any console log lines that seem to belong to the extension. Whether that means that it's not being loaded in the first place or not, I'm not sure about.

I tested this on Chrome, Firefox, Vivaldi and Opera GX. Same behaviour.

EDIT: I just read on discord that pokerogue broke the extension again yesterday. If that's related to my issue just close it.

EDIT 2: I tested your beta version that you linked on discord, it seems to work for me although it has some bugs. Those are different issues though, at least the extension loads and shows up. I'll leave this issue open for now for others to see until the issue is officially fixed. Just close it whenever you want.

**Comment by roguedex-dev** [comment]
I'll close it for now, let's see if the issue pops up again
