### ISSUE TITLE
Ability seems unable to detect it properly. 

### ISSUE THREAD

**Issue by Dynamixus** [roguedex-dev/roguedex#43]
Most of the time it's either NONE or STENCH. I'm using the Chrome extension.

**Comment by matheus-am4** [comment]
Same problem here (OPERA GX)

**Comment by ms-dc** [comment]
Same problem here (Opera GX).

**Comment by roguedex-dev** [comment]
Duplicate (and fixed locally alraedy)

**Comment by ms-dc** [comment]
![image](https://github.com/roguedex-dev/roguedex/assets/15190187/d784235e-9a4f-492b-9622-b0d2970b76da)

still either none or stench
