### ISSUE TITLE
Request: Change transparency of battle window

### ISSUE THREAD

**Issue by ArchOwlen** [roguedex-dev/roguedex#5]
This could also be a solution to #4 by making more of the screen visible

It would allow the plugin to still function, but not block any of the UI (especially on smaller screens)

**Comment by roguedex-dev** [comment]
Solved in 2.1

**Comment by ArchOwlen** [comment]
It would be nice if the background could be transparent, but leave the rest of the window full opacity ;3

(The current implementation makes everything transparent)

**Comment by roguedex-dev** [comment]
Which background do you mean then?

**Comment by ArchOwlen** [comment]
The dark background behind the sprite and type icons 

So all the information is still visible, but you can see through that part if it's in front of, say, the bottom right "fight, run, etc"

I'd say maybe the red/green/gray boxes behind the weaknesses(etc) stuff as well, but the main background may be enough 
(And it'd lose some user-friendlinees if you can't see the color)

**Comment by roguedex-dev** [comment]
![image](https://github.com/roguedex-dev/roguedex/assets/169194072/e0170359-da60-49ab-adb1-7ee260fb210d)

What do you think about something like this instead? I.e. the background color has some transparency by default, and then you can still regulate the overall opacity. (In the screenshot, opacity is at maximum, just the background is more transparent by default)

**Comment by ArchOwlen** [comment]
That is exactly what I was thinking! Just in regards to it being tied to the slider
It would be nice to see 2 separate sliders if we do the config menu idea ;3 

But I think this would be good as a start before that would be worked on

**Comment by roguedex-dev** [comment]
Included in  2.4
